version: '3'

services:
  sqlite3:
    image: brockramz/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  alembic-migrations:
    image: brainly/alembic-migrate
    command: -url=jdbc:sqlite://db/sceptre.db "upgrade head"

    volumes:
      - ./migrations:/versions
    links:
      - sqlite3
    depends_on:
      - sqlite3
